indumentaria/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
]

tienda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('indumentaria/', include('indumentaria.urls')),
]

indumentaria/models.py
from django.db import models

class Remera(models.Model):
    marca = models.CharField("Marca" , max_length=30)
    TALLES = (
        (1, "XS"),
        (2, "S"),
        (3, "M"),
        (4, "L"),
        (5, "XL"),
        (6, "XXL")
    )
    talle = models.PositiveSmallIntegerField("Talle", choices=TALLES)
    color = models.CharField("Color", max_length=15)
    precio = models.FloatField("Precio $")

indumentaria/views.py
from django.shortcuts import render
from .models import Remera

def index(request):
    remeras = Remera.objects.all()
    ctx = {'remeras': remeras}
    return render(request, "indumentaria/index.html", ctx)

indumentaria/templates/indumentaria/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'indumentaria/styles.css' %}">
    <title>Tienda</title>
</head>
<body>
    <h1>Indumentaria</h1>
    <h3>Remeras disponibles</h3>
    <table>
        <thead>
            <td>Marca</td> <!-- table data-->
            <td>Talle</td>
            <td>Color</td>
            <td>Precio</td>
        </thead>
        {% for remera in remeras %}
        <tr>  <!--- tr = table row-->
            <td>{{ remera.marca }}</td>
            <td>{{ remera.get_talle_display }}</td>
            <td>{{ remera.color }}</td>
            <td>$ {{ remera.precio }}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>